import datetime
import typing

from src import core
from src.todo.domain import todo, weekday, todos, month

__all__ = ("generate_holidays",)


def generate_holidays(user_id: int) -> typing.List[todo.Todo]:
    return [
        todos.Irregular(
            user_id=user_id,
            todo_id=-1,
            advance_days=30,
            category=core.TodoCategory.Reminder,
            date_added=datetime.date(1970, 1, 1),
            date_completed=None,
            description="Thanksgiving",
            month=month.Month.November,
            week_day=weekday.Weekday.Thursday,
            week_number=4,
            note="",
            start_date=datetime.date(1900, 1, 1),
        ),
        todos.Irregular(
            user_id=user_id,
            todo_id=-1,
            advance_days=30,
            category=core.TodoCategory.Reminder,
            date_added=datetime.date(1970, 1, 1),
            date_completed=None,
            description="Thanksgiving",
            month=month.Month.November,
            week_day=weekday.Weekday.Friday,
            week_number=4,
            note="",
            start_date=datetime.date(1900, 1, 1),
        ),
        todos.Yearly(
            user_id=user_id,
            todo_id=-1,
            advance_days=30,
            category=core.TodoCategory.Reminder,
            date_added=datetime.date(1970, 1, 1),
            date_completed=None,
            description="Christmas",
            month=month.Month.November,
            day=25,
            note="",
            start_date=datetime.date(1900, 1, 1),
        ),
        todos.Irregular(
            user_id=user_id,
            todo_id=-1,
            advance_days=30,
            category=core.TodoCategory.Reminder,
            date_added=datetime.date(1970, 1, 1),
            date_completed=None,
            description="Fathers Day",
            month=month.Month.June,
            week_day=weekday.Weekday.Sunday,
            week_number=3,
            note="",
            start_date=datetime.date(1900, 1, 1),
        ),
        todos.Irregular(
            user_id=user_id,
            todo_id=-1,
            advance_days=30,
            category=core.TodoCategory.Reminder,
            date_added=datetime.date(1970, 1, 1),
            date_completed=None,
            description="Mothers Day",
            month=month.Month.May,
            week_day=weekday.Weekday.Sunday,
            week_number=2,
            note="",
            start_date=datetime.date(1900, 1, 1),
        ),
        todos.Irregular(
            user_id=user_id,
            todo_id=-1,
            advance_days=30,
            category=core.TodoCategory.Reminder,
            date_added=datetime.date(1970, 1, 1),
            date_completed=None,
            description="Labor Day",
            month=month.Month.September,
            week_day=weekday.Weekday.Monday,
            week_number=1,
            note="",
            start_date=datetime.date(1900, 1, 1),
        ),
        todos.Irregular(
            user_id=user_id,
            todo_id=-1,
            advance_days=30,
            category=core.TodoCategory.Reminder,
            date_added=datetime.date(1970, 1, 1),
            date_completed=None,
            description="Martin Luther King Jr. Day",
            month=month.Month.January,
            week_day=weekday.Weekday.Monday,
            week_number=3,
            note="",
            start_date=datetime.date(1900, 1, 1),
        ),
        todos.Yearly(
            user_id=user_id,
            todo_id=-1,
            advance_days=30,
            category=core.TodoCategory.Reminder,
            date_added=datetime.date(1970, 1, 1),
            date_completed=None,
            description="New Year's Day",
            month=month.Month.January,
            day=1,
            note="",
            start_date=datetime.date(1900, 1, 1),
        ),
        todos.Irregular(
            user_id=user_id,
            todo_id=-1,
            advance_days=30,
            category=core.TodoCategory.Reminder,
            date_added=datetime.date(1970, 1, 1),
            date_completed=None,
            description="Presidents' Day",
            month=month.Month.February,
            week_day=weekday.Weekday.Monday,
            week_number=3,
            note="",
            start_date=datetime.date(1900, 1, 1),
        ),
        todos.Easter(
            user_id=user_id,
            todo_id=-1,
            advance_days=30,
            category=core.TodoCategory.Reminder,
            date_added=datetime.date(1970, 1, 1),
            date_completed=None,
            description="Easter",
            note="",
            start_date=datetime.date(1900, 1, 1),
        ),
    ]
